// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtD7NVdS8ExYMV1b2NquhzqracrjLL5l8',
    appId: '1:129583430741:web:3f9870e320298477f328dc',
    messagingSenderId: '129583430741',
    projectId: 'crypted-8468f',
    authDomain: 'crypted-8468f.firebaseapp.com',
    storageBucket: 'crypted-8468f.firebasestorage.app',
    measurementId: 'G-3XX5MFXQ85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDulqa7QJUuFaXAfcd0xM0uDusC6lvqyc4',
    appId: '1:129583430741:android:c85f747891671468f328dc',
    messagingSenderId: '129583430741',
    projectId: 'crypted-8468f',
    storageBucket: 'crypted-8468f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkUko_aEXVJsMnavvKYixO78rtVueZUCA',
    appId: '1:129583430741:ios:c196cea3b447779df328dc',
    messagingSenderId: '129583430741',
    projectId: 'crypted-8468f',
    storageBucket: 'crypted-8468f.firebasestorage.app',
    iosBundleId: 'com.example.cryptedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkUko_aEXVJsMnavvKYixO78rtVueZUCA',
    appId: '1:129583430741:ios:c196cea3b447779df328dc',
    messagingSenderId: '129583430741',
    projectId: 'crypted-8468f',
    storageBucket: 'crypted-8468f.firebasestorage.app',
    iosBundleId: 'com.example.cryptedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtD7NVdS8ExYMV1b2NquhzqracrjLL5l8',
    appId: '1:129583430741:web:f3da1b746df00663f328dc',
    messagingSenderId: '129583430741',
    projectId: 'crypted-8468f',
    authDomain: 'crypted-8468f.firebaseapp.com',
    storageBucket: 'crypted-8468f.firebasestorage.app',
    measurementId: 'G-LC1257PL0D',
  );

}